'use client';

import { useAppDispatch } from '@/lib/redux/hooks';
import {
  addToast,
  dismissToast,
  dismissAllToasts,
  showSuccessToast,
  showErrorToast,
  showWarningToast,
  showInfoToast,
  type Toast,
} from '@/lib/redux/slices/toastSlice';

export function useReduxToast() {
  const dispatch = useAppDispatch();

  // General toast function
  const toast = (props: Omit<Toast, 'id'>) => {
    dispatch(addToast(props));
    return {
      id: '', // The ID is generated by the reducer, so we don't have access to it here
      dismiss: () => {}, // Cannot dismiss without ID
      update: () => {}, // Cannot update without ID
    };
  };

  // Specialized toast functions
  const success = (props: Omit<Toast, 'id' | 'variant'>) => {
    dispatch(showSuccessToast(props));
  };

  const error = (props: Omit<Toast, 'id' | 'variant'>) => {
    dispatch(showErrorToast(props));
  };

  const warning = (props: Omit<Toast, 'id' | 'variant'>) => {
    dispatch(showWarningToast(props));
  };

  const info = (props: Omit<Toast, 'id' | 'variant'>) => {
    dispatch(showInfoToast(props));
  };

  // Dismiss functions
  const dismiss = (toastId?: string) => {
    if (toastId) {
      dispatch(dismissToast(toastId));
    } else {
      dispatch(dismissAllToasts());
    }
  };

  return {
    toast,
    success,
    error,
    warning,
    info,
    dismiss,
  };
}

export { toast } from '@/lib/redux/slices/toastSlice';
