#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔍 Running lint check..."
pnpm lint

echo "🧪 Running type check..."
pnpm tsc --noEmit

echo "🧪 Running tests..."
pnpm test

echo "🏗️ Running build..."
pnpm build 